const img = (...ids) => ids.map(id => ({ image: `assets/items/${id}.jpg`, thumb: `assets/thumbs/${id}.jpg`, original: `${id.toUpperCase()}` }));
const items = [
 {id:'bedroom-set-ornate-queen',title:'Ornate Queen Bedroom Set',category:'Bedroom Furniture',room:'Primary Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0491.jpg',photos:img('img_0490','img_0491','img_0492','img_0493','img_0494','img_0495','img_0496','img_0497'),description:'Large coordinated bedroom set with carved wood details, paneled headboard, matching footboard/rails, dresser, and nightstand pieces. Traditional statement style with substantial presence.',notes:['Includes multiple matching pieces shown in photos','Ornate carved wood and upholstered/nailhead details','Best for buyer pickup with adequate vehicle/help']},
 {id:'carved-upholstered-chaise',title:'Carved Upholstered Chaise Lounge',category:'Living Room',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0499.jpg',photos:img('img_0498','img_0499'),description:'Decorative chaise lounge with carved wood frame, rolled end, and patterned upholstery. A strong accent piece for a bedroom, sitting room, or entry area.',notes:['Traditional carved frame','Patterned fabric upholstery','Buyer should inspect fabric condition in person']},
 {id:'metal-scroll-dining-chair',title:'Metal Scroll Accent / Dining Chair',category:'Chairs',room:'Dining Area',status:'Available',price:'Make offer',hero:'assets/items/img_0506.jpg',photos:img('img_0500','img_0506','img_0507','img_0508'),description:'Black metal chair with scrollwork back and upholstered patterned seat. Useful as an accent chair, desk chair, or dining chair.',notes:['Decorative black metal frame','Light patterned cushion','Single chair shown']},
 {id:'gvm-led-video-light-kit',title:'GVM LED Video Light Kit',category:'Electronics',room:'Equipment',status:'Available',price:'Make offer',hero:'assets/items/img_0501.jpg',photos:img('img_0501','img_0502','img_0503','img_0512'),description:'GVM LED panel light setup with barn doors and stand shown. Useful for video, photography, streaming, or product lighting.',notes:['Includes visible GVM light panel and stand','Power/accessories should be confirmed in person','Good candidate for quick function test at sale']},
 {id:'oval-glass-coffee-table',title:'Oval Glass Coffee Table',category:'Tables',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0504.jpg',photos:img('img_0504','img_0505'),description:'Oval glass-top coffee table with decorative metal base. Light visual footprint and classic styling for a living room or sitting area.',notes:['Glass oval top','Decorative metal base','Inspect glass edge and surface in person']},
 {id:'patterned-club-chair',title:'Patterned Club Chair',category:'Chairs',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0509.jpg',photos:img('img_0509','img_0510','img_0511','img_0523','img_0524','img_0525'),description:'Upholstered club chair with bold geometric/patterned fabric and dark turned front legs. Distinctive accent seating.',notes:['Bold patterned upholstery','Compact club-chair profile','Fabric condition visible in photos; inspect in person']},
 {id:'red-loveseat',title:'Red Upholstered Loveseat',category:'Sofas & Loveseats',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0513.jpg',photos:img('img_0513','img_0514','img_0515','img_0519','img_0520','img_0521','img_0522'),description:'Red loveseat with rolled arms and skirted base. Comfortable small sofa size for a living room, office, or bedroom sitting area.',notes:['Two-seat loveseat proportions','Rolled-arm traditional silhouette','Some close-up photos included for inspection']},
 {id:'floral-wingback-chair',title:'Floral Wingback Accent Chair',category:'Chairs',room:'Bedroom / Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0516.jpg',photos:img('img_0516','img_0517','img_0518'),description:'Light floral upholstered wingback-style accent chair with curved arms and shaped back. Soft cottage/traditional look.',notes:['Light floral fabric','Wingback-inspired shape','Good bedroom or reading-chair candidate']},
 {id:'gray-sectional-ottoman',title:'Gray Sectional Sofa with Ottoman',category:'Sofas & Loveseats',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0528.jpg',photos:img('img_0526','img_0527','img_0528','img_0529'),description:'Gray sectional sofa with chaise-style section and matching ottoman. Casual family-room seating with soft upholstery.',notes:['Sectional plus ottoman shown','Gray fabric upholstery','Buyer should verify dimensions and fabric wear in person']},
 {id:'plant-stand-artificial-tree',title:'Artificial Tree with Plant Stand',category:'Decor',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0530.jpg',photos:img('img_0530','img_0531','img_0532','img_0574','img_0575'),description:'Tall artificial greenery/tree with planter and stand shown in multiple rooms. Adds height and greenery without maintenance.',notes:['Artificial greenery','Planter/stand shown','Decorative indoor use']},
 {id:'dark-wood-bed',title:'Dark Wood Bed Frame',category:'Bedroom Furniture',room:'Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0535.jpg',photos:img('img_0533','img_0534','img_0535'),description:'Dark wood bed frame with carved posts and arched headboard/footboard styling. Traditional bedroom piece with substantial wood presence.',notes:['Dark wood frame','Carved post details','Mattress/bedding not represented as included unless confirmed']},
 {id:'white-wicker-vanity-nightstand',title:'White Wicker Vanity / Nightstand with Mirror',category:'Bedroom Furniture',room:'Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0536.jpg',photos:img('img_0536','img_0537','img_0538','img_0539','img_0540','img_0541'),description:'White wicker-style vanity or nightstand with drawers, glass-like top detail, and matching mirror. Light coastal/cottage style.',notes:['Drawer storage shown','Mirror included in photos','Good bedroom, guest room, or vanity use']},
 {id:'wood-bed-green-room',title:'Wood Bed Frame - Green Room',category:'Bedroom Furniture',room:'Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0543.jpg',photos:img('img_0542','img_0543','img_0544'),description:'Wood bed frame with turned posts and curved headboard in the green bedroom. Traditional warm wood finish.',notes:['Turned post details','Curved headboard','Confirm bed size in person']},
 {id:'dollhouse-playset',title:'Dollhouse Playset with Accessories',category:'Kids & Toys',room:'Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0545.jpg',photos:img('img_0545'),description:'Multi-level dollhouse playset with visible toy furniture and accessories. Colorful children’s play item.',notes:['Accessories shown in photo','Buyer should confirm completeness','Good kids/toy listing']},
 {id:'large-gold-framed-mirror',title:'Large Ornate Gold Framed Mirror',category:'Wall Decor',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0547.jpg',photos:img('img_0547','img_0548','img_0549','img_0550','img_0551'),description:'Large wall mirror with ornate gold-tone frame and carved corner detailing. Strong decorative focal point for entry, dining, or living room.',notes:['Large mirror','Ornate gold-tone frame','Transport carefully; buyer should bring padding']},
 {id:'brother-1034dx-serger',title:'Brother 1034DX Serger Sewing Machine',category:'Crafts & Sewing',room:'Sewing / Utility',status:'Available',price:'Make offer',hero:'assets/items/img_0554.jpg',photos:img('img_0553','img_0554'),description:'Brother 1034DX serger sewing machine with original box shown. Useful for sewing, garment finishing, and craft projects.',notes:['Model 1034DX visible on box','Machine shown separately','Power/function should be confirmed at sale']},
 {id:'framed-wall-art-group',title:'Framed Wall Art Group',category:'Wall Decor',room:'Throughout House',status:'Available',price:'Make offer',hero:'assets/items/img_0558.jpg',photos:img('img_0557','img_0558','img_0559','img_0561','img_0577'),description:'Assortment of framed wall art including floral prints, portrait-style art, inspirational/decorative panel, and larger framed scene.',notes:['Multiple framed pieces shown','Can be sold separately or as a group','Inspect frame/glass condition in person']},
 {id:'round-metal-wall-decor',title:'Round Metal Wall Decor',category:'Wall Decor',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0560.jpg',photos:img('img_0560','img_0562'),description:'Round metal wall decor with scroll/floral pattern and dark finish. Lightweight decorative wall accent.',notes:['Round metal design','Dark finish','Two angles shown']},
 {id:'table-lamp-black-shade',title:'Table Lamp with Black Shade',category:'Lighting',room:'Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0563.jpg',photos:img('img_0563','img_0564'),description:'Table lamp with dark base and black shade, photographed working. Suitable for bedroom, side table, or office lighting.',notes:['Lamp shown illuminated','Black shade','Confirm bulb/power at sale']},
 {id:'cream-highback-chair',title:'Cream High-Back Upholstered Chair',category:'Chairs',room:'Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0565.jpg',photos:img('img_0565','img_0566'),description:'Cream upholstered high-back chair with subtle damask-style pattern and rolled arms. Formal accent chair for bedroom or sitting area.',notes:['Light neutral upholstery','High-back profile','Inspect fabric condition in person']},
 {id:'marble-top-nightstand',title:'Ornate Marble-Top Nightstand',category:'Bedroom Furniture',room:'Bedroom',status:'Available',price:'Make offer',hero:'assets/items/img_0567.jpg',photos:img('img_0567','img_0568'),description:'Dark ornate nightstand or side table with marble-look top and drawer/storage detail. Coordinates with traditional bedroom furniture.',notes:['Marble-look top','Drawer shown open','Carved dark wood styling']},
 {id:'small-metal-side-tables',title:'Pair of Small Metal Side Tables',category:'Tables',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0570.jpg',photos:img('img_0570'),description:'Small metal side/accent tables with light tops and slender frames. Useful as plant stands, end tables, or small patio-style accents.',notes:['Two small tables shown','Metal frame construction','Compact footprint']},
 {id:'decorative-figurines-lot',title:'Decorative Figurines & Tabletop Decor Lot',category:'Decor',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0571.jpg',photos:img('img_0571','img_0572','img_0573','img_0578','img_0579','img_0580','img_0581','img_0582','img_0592','img_0593'),description:'Mixed tabletop decor including figurines, lamps, gold pineapple pieces, rooster/chicken decor, small clock, and assorted decorative accents.',notes:['Mixed decor lot; individual items may sell separately','Good for browsing during sale','Exact contents should be verified in person']},
 {id:'rose-wall-panel',title:'Rose Wall Panel Art',category:'Wall Decor',room:'Living Room',status:'Available',price:'Make offer',hero:'assets/items/img_0576.jpg',photos:img('img_0576'),description:'Large square wall panel with raised rose design in deep red/brown tones. Textured decorative statement piece.',notes:['Textured floral panel','Square format','Warm dark finish']},
 {id:'garage-tools-ladders-lot',title:'Garage Tools, Ladders & Household Lot',category:'Garage & Tools',room:'Garage',status:'Available',price:'Make offer',hero:'assets/items/img_0585.jpg',photos:img('img_0583','img_0584','img_0585','img_0586','img_0587','img_0588','img_0589','img_0590','img_0591'),description:'Mixed garage and household items including ladders, storage drawers, yard/cleaning tools, hoses/tubing, small appliances, and utility items.',notes:['Mixed garage lot; inspect in person','Werner ladder visible','Some items may be sold individually']},
 {id:'outdoor-planters-yard-items',title:'Outdoor Planters & Yard Items',category:'Outdoor',room:'Outside',status:'Available',price:'Make offer',hero:'assets/items/img_0594.jpg',photos:img('img_0594','img_0595','img_0596','img_0597','img_0598'),description:'Outdoor items including ceramic planters, green spreader/cart, and perforated metal lantern or planter-style pieces.',notes:['Outdoor/patio items','Several planters shown','Condition best evaluated outside at sale']}
];
require('fs').writeFileSync('items.js', `window.SALE_ITEMS = ${JSON.stringify(items, null, 2)};\n`, 'utf8');
console.log(`wrote ${items.length} grouped listings`);
